# Generated by Django 4.2.6 on 2023-10-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "URGENT"),
                    ("High", "HIGH"),
                    ("Medium", "MEDIUM"),
                    ("Low", "LOW"),
                ],
                default="Low",
                max_length=6,
            ),
        ),
    ]
